### ISSUE TITLE
Your platform dose not support yet, AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD

### ISSUE THREAD

**Issue by sidharthaprusty** [SharpAI/DeepCamera#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Supportfor AMD64 Family 23 Model 96

**Describe alternatives you've considered**

**Additional context**

**Comment by Usher09896** [comment]
This issue should be fixed by new release:
https://github.com/SharpAI/sharpai_hub/releases/tag/0.1.43

please upgrade with following command:
```
pip3 install --upgrade sharpai-hub
```

Let's know if it fixes this issue.
