### ISSUE TITLE
My side need to support the s3 storage or other

### ISSUE THREAD

**Issue by yufeng2015** [SharpAI/DeepCamera#11]
**hello!**

> My side need to support the s3 storage or other, but need to know the current logic of uploading files, so that together

1. Only the following file?
> https://github.com/SharpAI/DeepCamera/blob/master/src/detector/upload.js

2. The following two is the key method?Who is calling them?
 
> ![image](https://user-images.githubusercontent.com/11326721/54248965-6a66eb80-4579-11e9-8dad-f2b4274b327e.png)

**Comment by solderzzc** [comment]
The upload interface is defined here:
https://github.com/SharpAI/DeepCamera/blob/master/src/detector/upload.js#L127

you can add a new file to implement it, after then, import in the up layer module with ENV control or setting file.

**Comment by yufeng2015** [comment]
‘’putFileAliyun‘’，‘ getAccessUrl’，Who is calling them?

**Comment by solderzzc** [comment]
please reopen if still have question.
