### ISSUE TITLE
Better site UI? (ymmv)

### ISSUE THREAD

**Issue by macginitie** [SharpAI/DeepCamera#12]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when line breaks are funky & tenses are incosistent.

**Describe the solution you'd like**
Change the text in the 2nd box in lifecycle.png: from PreProc [\n] essing to Pre- [\n] Process

... because it's not Labeling, Training, Model Deploying

**Additional context**
![image](https://user-images.githubusercontent.com/40873334/54323778-b8571000-45c8-11e9-837b-97720b99c5c2.png)

**Comment by macginitie** [comment]
incoNsistent :-p

**Comment by solderzzc** [comment]
Oh, @macginitie  that's great suggestion :)

**Comment by solderzzc** [comment]
I was thinking about this ugly thing in 1sec, but no better ides :)

**Comment by macginitie** [comment]
I'll just say, I like the clean look of all boxes being the same size :)

**Comment by solderzzc** [comment]
@macginitie Thanks a lot, just updated :) Reopen if still has issue lol

**Comment by solderzzc** [comment]
hmm, the CDN cache still loading the previous image.

**Comment by solderzzc** [comment]
Yep, done for now. please check @macginitie
