### ISSUE TITLE
run on 3288 or 3399 ， ‘/data/data/com.termux/files/home/.ro_serialno’ is null

### ISSUE THREAD

**Issue by yufeng2015** [SharpAI/DeepCamera#27]
run on 3288 or 3399 ， ‘/data/data/com.termux/files/home/.ro_serialno’ is null.

For the moment, the added manually, can also work. Where the code is generated '. Ro_serialno '?

**Comment by solderzzc** [comment]
This file `.ro_serialno` is created in Termux_Launcher. 

https://github.com/SharpAI/Launcher_Termux/blob/master/app/src/main/java/com/termux/app/TermuxActivity.java#L685

**Comment by solderzzc** [comment]
Fixed.
