### ISSUE TITLE
新编译打包代码log有error

### ISSUE THREAD

**Issue by fay1986** [SharpAI/DeepCamera#44]
![image](https://user-images.githubusercontent.com/40154708/57755176-c6d5bb00-7722-11e9-8897-5bb0d8d60e4d.png)

**Comment by fay1986** [comment]
@solderzzc

**Comment by solderzzc** [comment]
@ningning-718 Please follow up. 
Thanks for your reporting @fay1986

**Comment by solderzzc** [comment]
fixed, thx
