### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by jeff-h** [SharpAI/DeepCamera#48]
Your project looks quite amazing and I'd love to have a play with it, but am not really sure where to start. I don't have a sufficiently capable Android device so would like to try the Docker build, but I don't really want to use Shinobi.

I'm unclear how DeepCamera interacts with Shinobi — would it be possible to use DeepCamera in conjunction with other apps such as MotionEye or Home Assistant?

**Comment by solderzzc** [comment]
@jeff-h Thanks for the interesting in DeepCamera.
With docker build, shinobi provides configuration UI to your ip camera. When shinobi saved/captured image from your camera stream, DeepCamera will handle the other parts.
