### ISSUE TITLE
Support for Jetson nano?

### ISSUE THREAD

**Issue by SaddamBInSyed** [SharpAI/DeepCamera#55]
Hi there.

thanks for your works.

I am a newbie to this repo. I would like to know whether I can run this DeepCamera in my Jetson nano?

please advise.

**Comment by solderzzc** [comment]
hi, @SaddamBInSyed welcome to community, DeepCamera can run in Jetson Nano by source code but need change scripts to fit system. 
https://github.com/SharpAI/DeepCamera/blob/master/scripts/start_service.sh
I can built ARM64v8 docker to save the manually effort in weeks. :)

**Comment by SaddamBInSyed** [comment]
thanks for your response.
I will wait for the same.

**Comment by solderzzc** [comment]
just finished the build file on branch `arm64v8`, Travis CI will build images, then you can have a try 

https://travis-ci.org/github/SharpAI/DeepCamera

**Comment by SaddamBInSyed** [comment]
@solderzzc 
thanks for sharing and letting me know.

**Comment by solderzzc** [comment]
@SaddamBInSyed did you have chance to run DeepCamera on Nano? you can use DeepCamera/run-on-arm64v8.sh to start services, let me know if any issues.

**Comment by solderzzc** [comment]
close for now
