### ISSUE TITLE
not running on pi-4

### ISSUE THREAD

**Issue by MohaBeacon** [SharpAI/DeepCamera#58]
got disabled ssh,vnc, stopped streaming too

**Comment by solderzzc** [comment]
it is heavily memory load, I tested on 8GB pi-4 version

MohaBeacon <notifications@github.com> 于 2020年10月4日周日 下午3:04写道：

**Comment by solderzzc** [comment]
Summary(conversation on [slack](https://sharpai-invite-automation.herokuapp.com/)): 
1. works out of box if you have 8GB memory version of Raspberry-pi.
2. you need at least 4GB memory version of Raspberry-Pi, please add 2GB swap to run services.

**Comment by solderzzc** [comment]
close this one
