### ISSUE TITLE
Exec format error on raspberry pi

### ISSUE THREAD

**Issue by mykiscool** [SharpAI/DeepCamera#61]
**Describe the bug**
when I run the start command, I get an exec format error.
Here's the terminal output

`sudo ./start-cloud.sh start
starting...
Stopping api_server ... done
Stopping minio      ... done
Stopping broker     ... done
Starting api_server ... done
Starting minio      ... done
Starting broker     ... done
Attaching to api_server, minio, broker
api_server    | standard_init_linux.go:211: exec user process caused "exec format error"
broker        | standard_init_linux.go:211: exec user process caused "exec format error"
minio         | standard_init_linux.go:211: exec user process caused "exec format error"
api_server exited with code 1
broker exited with code 1
api_server    | standard_init_linux.go:211: exec user process caused "exec format error"`

**To Reproduce**
Run the start script on a vanilla raspbian buster on raspberry pi 4 B with only docker and docker compose installed

**Expected behavior**
This is the first time running this, but I'm guessing I probably shouldn't see this error.

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by solderzzc** [comment]
Hi, @mykiscool 
Thanks for sharing the detail of your reporting. you need to run start-cloud.sh on your X86 server or AWS to deploy your own private cloud. currently the private cloud server doesn't support arm architecture...


<img width="809" alt="Screen Shot 2020-10-11 at 11 36 44 AM" src="https://user-images.githubusercontent.com/3085564/95669720-163d4680-0bb6-11eb-8ff1-9e1ccc0dd272.png">
