### ISSUE TITLE
Your secret keys are public

### ISSUE THREAD

**Issue by Ajaykumbhare** [SharpAI/DeepCamera#69]
**Your secret keys are public**
I can see your secret keys in this URL and This can be dangerous. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17526893/153634207-dbf106be-69be-4373-bab1-2f9dca4479a0.png">

**To Reproduce**
1. Go to this [link](https://github.com/SharpAI/DeepCamera/blob/2d8182cb0e9b0ecf6361056add2d30e764cb7619/docker/aws.env)

**Expected behavior**
You shouldn't store this info in file

**Comment by solderzzc** [comment]
Thanks for reporting this issue, we are deploying self maintained storage server which is compatible with AWS, so it's not AWS keys.
