### ISSUE TITLE
Survey for development kit supply

### ISSUE THREAD

**Issue by solderzzc** [SharpAI/DeepCamera#8]
Due to the hardware delivery will cost our extra effort, we want to know if this is needed.

Full set development kit will contain:

- Rockchip RK3288 set-up-box with deep camera software 2GB mem, 8GB Flash
- Dahua Camera

Please thumb up if you need it.

**Comment by chensteven** [comment]
What is the cost?

**Comment by solderzzc** [comment]
@chensteven It cost around  ¥400(RK3288 Box) + ¥120 (Dahua Camera) + ¥100 (extra components) in China. We don't have experience on the handling of shipping/preparation, but would run as non-profit on hardware, estimated $100(hw cost) + $15(shipping) +$20(handling fee).

**Comment by Paraesthetic** [comment]
Sounds interesting

**Comment by samsomlan** [comment]
how to contact you?  I have a lot  interesting about your project。

**Comment by solderzzc** [comment]
@samsomlan please join our slack ;)

https://sharpai-invite-automation.herokuapp.com/
